export const VOLUNTEER_PROFESSIONS = [
  "Legal Professional & Advocate",
  "Doctor & Healthcare Specialist",
  "Nursing & Allied Health Professional",
  "Pharmacist & Chemist",
  "Counselor & Mental Health Expert",
  "Chartered Accountant & Corporate Secretary",
  "Financial Advisor & Banking Specialist",
  "IT & Software Engineering Professional",
  "Teacher & Education Specialist",
  "Social Worker & NGO Administrator",
  "Engineer & Architect",
  "Scientific Researcher",
  "Agriculture & Farming Expert",
  "Police & Defense Personnel",
  "Student & Youth Leader",
  "Journalist & Media Specialist",
  "Business Owner & Entrepreneur",
  "Management Consultant",
  "Civil Servant & Government Officer",
  "Artist & Creative Professional",
  "Sportsperson & Fitness Trainer",
  "Veterinarian & Animal Welfare Expert",
  "Logistics & Transport Specialist",
  "Skilled Technician & Tradesperson",
  "HR & Talent Development Specialist",
  "Real Estate & Property Advisor",
  "Homemaker & Community Organizer",
  "Spiritual Leader & Guidance Counselor",
  "Environmental Scientist & Conservationist",
  "Other",
] as const;

export type VolunteerProfession = typeof VOLUNTEER_PROFESSIONS[number];

export const PROFESSION_SPECIALTIES: Record<string, string[]> = {
  "Legal Professional & Advocate": [
    "Criminal Law & FIR Assistance",
    "Civil & Property Dispute Resolution",
    "Family Law & Domestic Violence Support",
    "Labour & Employment Rights",
    "Consumer Protection & RERA Guidance",
    "RTI Filing & Public Interest Litigation",
    "Cyber Law & Online Fraud Advisory",
    "Constitutional Rights & Civic Liberties",
    "Corporate Law & MSME Compliance",
  ],
  "Doctor & Healthcare Specialist": [
    "General Medicine & OPD Support",
    "Pediatric & Maternal Health",
    "Emergency & Trauma Care",
    "Dental & Ophthalmology Camps",
    "Dermatology & Skin Health Awareness",
    "Orthopedic & Physiotherapy Support",
    "Ayush & Alternative Medicine (Ayurveda, Homeopathy)",
    "Community Preventive Medicine & Public Health",
  ],
  "Nursing & Allied Health Professional": [
    "Emergency First Aid & Triage",
    "ICU & Critical Care Nursing",
    "Community Vaccination & Immunization Drives",
    "Home Care & Geriatric Nursing",
    "Midwifery & Antenatal Care",
    "Blood Donation Camp Coordination",
    "Health Education & Sanitation Awareness",
  ],
  "Pharmacist & Chemist": [
    "Generic Drug Awareness & Jan Aushadhi Guidance",
    "Prescription Review & Drug Interaction Advisory",
    "Free Health Camp Drug Dispensation",
    "Substance Abuse & De-addiction Awareness",
    "Nutrition & Supplement Advisory",
    "Pharmaceutical Waste & Safe Disposal Training",
  ],
  "Counselor & Mental Health Expert": [
    "Clinical Psychology & Psychiatric Counseling",
    "Child & Adolescent Mental Health",
    "Family & Marital Counseling",
    "Suicide Prevention & Crisis Intervention",
    "Addiction & Substance De-addiction",
    "Workplace Stress & Burnout Recovery",
    "Trauma & PTSD Support",
    "Career & Academic Counseling",
  ],
  "Chartered Accountant & Corporate Secretary": [
    "Income Tax & ITR Filing Assistance",
    "GST Registration & Compliance",
    "NGO & Trust Audit & 80G/12A Compliance",
    "Company Incorporation & ROC Filing",
    "MSME & Startup Registration Support",
    "Financial Statement Literacy Workshops",
    "Forensic Accounting & Fraud Detection",
  ],
  "Financial Advisor & Banking Specialist": [
    "Personal Finance & Savings Planning",
    "Jan Dhan, Sukanya Samriddhi & Government Scheme Enrollment",
    "Mutual Fund & SIP Awareness",
    "Micro-Finance & Self-Help Group Support",
    "Insurance (Life, Health, Crop) Awareness & Claims",
    "Loan & Credit Score Advisory",
    "Digital Payment, UPI & Net Banking Training",
  ],
  "IT & Software Engineering Professional": [
    "Software Development & Web/App Engineering",
    "Cybersecurity & Online Fraud Prevention",
    "Data Science & Analytics",
    "Cloud Computing & Infrastructure",
    "Digital Literacy & Basic Computer Training",
    "E-Governance, Aadhaar & DigiLocker Assistance",
    "AI / ML Awareness & Ethical Tech",
    "Open Source & Community Tech Projects",
  ],
  "Teacher & Education Specialist": [
    "Primary & Secondary School Tutoring",
    "Higher Education & University Mentoring",
    "Competitive Exam Coaching (UPSC, SSC, Banking)",
    "Special Needs & Inclusive Education",
    "STEM & Science Olympiad Preparation",
    "Vocational & Skill Development Training",
    "Adult Literacy & Continuing Education",
    "Language & Communication Skills (English, Hindi, Regional)",
  ],
  "Social Worker & NGO Administrator": [
    "Emergency & Disaster Relief Coordination",
    "Slum & Urban Grassroots Outreach",
    "Rural Development & Panchayat Liaison",
    "Women & Child Empowerment Programs",
    "SC/ST/OBC Welfare & Tribal Development",
    "Rehabilitation & Migrant Worker Support",
    "Anti-Trafficking & Human Rights Fieldwork",
    "Voter Awareness & Electoral Literacy Campaigns",
  ],
  "Engineer & Architect": [
    "Civil Engineering & Structural Safety Audit",
    "Mechanical & Industrial Engineering Support",
    "Electrical & Power Infrastructure",
    "Urban Planning & Smart City Advisory",
    "Water Supply, Sanitation & Drainage Solutions",
    "Renewable Energy & Solar Installation",
    "Road Safety & Transport Infrastructure",
    "Affordable Housing & PMAY Guidance",
  ],
  "Scientific Researcher": [
    "Environmental Science & Pollution Research",
    "Agricultural Science & Crop Research",
    "Biotechnology & Pharmaceutical Research",
    "Physics, Chemistry & Material Sciences",
    "Public Health & Epidemiology",
    "Space & Defense Technology (ISRO/DRDO Awareness)",
    "STEM Education & Science Communication",
    "Innovation, Patent Filing & IPR Awareness",
  ],
  "Agriculture & Farming Expert": [
    "Kharif & Rabi Crop Advisory",
    "Organic & Natural Farming (Zero Budget)",
    "Horticulture, Floriculture & Plantation Crops",
    "Dairy Farming & Animal Husbandry",
    "Fisheries & Aquaculture",
    "Soil Health, Irrigation & Water Management",
    "Government Schemes (PM-KISAN, PMFBY, KCC)",
    "Farm Mechanization & Modern Techniques",
    "Market Linkage, MSP & Mandi Operations",
    "Farmer Producer Organization (FPO) Formation",
  ],
  "Police & Defense Personnel": [
    "Community Policing & Neighborhood Watch",
    "Women Safety & Self-Defense Training",
    "Anti-Drug & Anti-Ragging Awareness",
    "Cybercrime Reporting & Digital Safety",
    "Disaster Relief & Rescue Operations",
    "Traffic Management & Road Safety",
    "Ex-Servicemen Welfare & Pension Guidance",
    "National Security & Border Awareness Programs",
  ],
  "Student & Youth Leader": [
    "Event & Field Logistics",
    "Campus Awareness & Local Campaigning",
    "Social Media & Digital Outreach",
    "Peer Mentoring & Study Circles",
    "NSS / NCC / Civic Volunteer Programs",
    "Youth Parliament & Debate Facilitation",
    "Environmental & Swachh Bharat Drives",
    "Startup & Innovation Club Coordination",
  ],
  "Journalist & Media Specialist": [
    "Print & Electronic Media Reporting",
    "Investigative & Ground-Level Journalism",
    "Social Media Strategy & Content Creation",
    "Documentary & Community Storytelling",
    "Fact Checking & Misinformation Alerts",
    "Public Relations & Press Event Management",
    "Media Literacy & Responsible Reporting",
    "Regional Language & Vernacular Content",
  ],
  "Business Owner & Entrepreneur": [
    "Event Sponsorship & CSR Partnerships",
    "Local Business & MSME Mentorship",
    "Startup Incubation & Funding Guidance",
    "Employment Generation & Skill Training",
    "Supply Chain & Vendor Coordination",
    "Export-Import & Trade Facilitation",
    "Digital Commerce & E-Commerce Guidance",
  ],
  "Management Consultant": [
    "Operations & Project Management",
    "Strategy & Business Development",
    "Volunteer Team Leadership & Training",
    "Impact Assessment & Program Evaluation",
    "Grant Writing & Donor Management",
    "Change Management & Process Optimization",
    "Quality Assurance & ISO Compliance",
  ],
  "Civil Servant & Government Officer": [
    "IAS / IPS / IFS Administrative Guidance",
    "Public Welfare Scheme Enrollment (MGNREGA, Ayushman Bharat)",
    "Panchayat & Municipal Administration Liaison",
    "Revenue, Land Records & Mutation Assistance",
    "Pension, Gratuity & Retirement Benefits Guidance",
    "E-Governance & Public Service Delivery",
    "Policy Awareness & Citizen Rights Education",
    "Community Dispute Resolution & Lok Adalat Mediation",
  ],
  "Artist & Creative Professional": [
    "Graphic Design & Campaign Visual Identity",
    "Photography & Videography",
    "Traditional Art, Handicraft & Folk Art Preservation",
    "Theatre, Dance & Performing Arts",
    "Music & Cultural Event Curation",
    "Interior & Exhibition Design",
    "Creative Workshops for Underprivileged Youth",
  ],
  "Sportsperson & Fitness Trainer": [
    "Cricket, Football & Team Sports Coaching",
    "Athletics, Kabaddi & Traditional Indian Sports",
    "Yoga & Meditation Instruction",
    "Gymnasium & Personal Fitness Training",
    "Martial Arts & Self-Defense Training",
    "Sports Nutrition & Diet Planning",
    "Inclusive Sports for Differently-Abled Citizens",
    "Youth Tournament & Sports Event Organization",
  ],
  "Veterinarian & Animal Welfare Expert": [
    "Pet Health & Small Animal Care",
    "Livestock & Cattle Health (Dairy, Poultry, Goat)",
    "Stray Animal Vaccination & ABC Sterilization",
    "Animal Cruelty Prevention & SPCA Coordination",
    "Wildlife Conservation & Habitat Protection",
    "Fisheries & Aquatic Animal Health",
    "Pet Adoption & Responsible Ownership Awareness",
  ],
  "Logistics & Transport Specialist": [
    "Road Safety & Accident Prevention",
    "Emergency Ambulance & Disaster Logistics",
    "Public Transport Accessibility & Planning",
    "Goods Transport, Warehousing & Cold Chain",
    "Fleet Management & Driver Training",
    "Last-Mile Delivery & Rural Connectivity",
    "EV Adoption & Green Transport Awareness",
  ],
  "Skilled Technician & Tradesperson": [
    "Electrical Wiring & Safety Installation",
    "Plumbing & Water Fitting",
    "Carpentry & Woodwork",
    "Welding & Metal Fabrication",
    "AC, Refrigeration & Appliance Repair",
    "Mobile & Computer Hardware Repair",
    "Solar Panel & Rainwater Harvesting Installation",
    "Vocational Training & ITI Apprenticeship Mentoring",
  ],
  "HR & Talent Development Specialist": [
    "Resume Building & Interview Preparation",
    "Soft Skills & Personality Development",
    "Volunteer Recruitment & Onboarding",
    "Labour Law & Employee Rights Awareness",
    "Diversity, Equity & Inclusion Programs",
    "Career Counseling & Job Placement Support",
    "Corporate Training & Team Building Facilitation",
  ],
  "Real Estate & Property Advisor": [
    "Affordable Housing & PMAY Scheme Guidance",
    "Tenant Rights & Rent Agreement Advisory",
    "Property Registration & Stamp Duty Guidance",
    "Land Revenue Records & Mutation Process",
    "RERA Compliance & Builder Dispute Resolution",
    "Urban Planning & Smart City Awareness",
    "Commercial Lease & Shop Act Advisory",
  ],
  "Homemaker & Community Organizer": [
    "Neighborhood Watch & Local Safety",
    "Community Kitchen & Meal Distribution (Langar, Bhandara)",
    "Women Self-Help Group (SHG) Formation & Mentoring",
    "Waste Segregation & Swachh Colony Campaigns",
    "Festival & Cultural Event Organization",
    "Child Care & After-School Activity Support",
    "Home Nutrition, First Aid & Family Wellness",
  ],
  "Spiritual Leader & Guidance Counselor": [
    "Interfaith Harmony & Peace Building",
    "De-addiction & Moral Rehabilitation",
    "Community Charity & Donation Drives",
    "Meditation, Yoga & Spiritual Wellness",
    "Last Rites & Bereavement Counseling",
    "Cultural Heritage & Temple/Mosque/Gurudwara Management",
    "Social Harmony & Anti-Superstition Awareness",
  ],
  "Environmental Scientist & Conservationist": [
    "Air & Water Quality Monitoring",
    "Tree Plantation & Urban Green Cover",
    "Solid Waste Management & Recycling",
    "Climate Change & Carbon Footprint Education",
    "River & Lake Cleanup & Rejuvenation",
    "Biodiversity Survey & Wildlife Corridor Protection",
    "Wetland & Mangrove Conservation",
    "Environmental Impact Assessment & Compliance",
  ],
  "Other": [
    "General Civic Support & Volunteering",
    "Event & Field Logistics",
    "Emergency Response & Relief Support",
    "Community Awareness & Outreach",
    "Administrative & Clerical Assistance",
    "Translation & Regional Language Support",
  ],
};

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi NCR",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;
