import {
  DashboardStats,
  ActivityItem,
  DonationRecord,
  DonationStats,
  RecurringDonation,
  TaxCertificate,
  ReferralMember,
  ReferralStats,
  MemberProfile,
  SupportTicket,
  FAQItem,
  VolunteerEligibility,
} from './types';

export const mockDashboardStats: DashboardStats = {
  totalDonated: 48500,
  totalReferrals: 12,
  campaignsJoined: 6,
  badgeLevel: 'Gold Citizen',
  eventsAttended: 8,
  volunteerStatus: 'not_applied',
};

export const mockActivityTimeline: ActivityItem[] = [
  {
    id: 'act_1',
    type: 'donation',
    title: 'Donated ₹5,000 to Clean Water Campaign',
    description: 'Payment successful via UPI.',
    date: '2026-05-24T10:30:00Z',
    amount: 5000,
    status: 'success',
  },
  {
    id: 'act_2',
    type: 'referral_donate',
    title: 'Referral Completed Donation',
    description: 'Priya Sharma (referred by you) made their first donation.',
    date: '2026-05-22T14:15:00Z',
  },
  {
    id: 'act_3',
    type: 'referral_join',
    title: 'New Referral Joined',
    description: 'Aarav Patel registered using your link.',
    date: '2026-05-21T09:00:00Z',
  },
  {
    id: 'act_4',
    type: 'event_register',
    title: 'Registered for Clean-up Drive',
    description: 'Event: Juhu Beach Cleanup on 2026-06-05.',
    date: '2026-05-18T16:45:00Z',
  },
  {
    id: 'act_5',
    type: 'donation',
    title: 'Recurring Donation Processed',
    description: 'Monthly contribution of ₹2,500 for Tribal Education.',
    date: '2026-05-10T00:00:00Z',
    amount: 2500,
    status: 'success',
  },
  {
    id: 'act_6',
    type: 'ticket_update',
    title: 'Support Ticket Resolved',
    description: 'Ticket SC-4820: "80G Certificate Generation Request" resolved by Support.',
    date: '2026-05-05T11:20:00Z',
  },
];

export const mockDonationRecords: DonationRecord[] = [
  {
    id: 'don_1',
    transactionId: 'TXN892348910',
    amount: 5000,
    purpose: 'Clean Water Campaign',
    paymentMethod: 'UPI (GPay)',
    status: 'success',
    date: '2026-05-24T10:30:00Z',
    receiptUrl: '/receipts/TXN892348910.pdf',
    taxCertificateUrl: '/certificates/80G-FY25-26.pdf',
  },
  {
    id: 'don_2',
    transactionId: 'TXN891273981',
    amount: 2500,
    purpose: 'Tribal Education support',
    paymentMethod: 'Credit Card (Visa)',
    status: 'success',
    date: '2026-05-10T00:00:00Z',
    receiptUrl: '/receipts/TXN891273981.pdf',
    taxCertificateUrl: '/certificates/80G-FY25-26.pdf',
  },
  {
    id: 'don_3',
    transactionId: 'TXN889234123',
    amount: 10000,
    purpose: 'Smart Citizen Core Support Fund',
    paymentMethod: 'Netbanking (HDFC)',
    status: 'success',
    date: '2026-04-15T18:22:00Z',
    receiptUrl: '/receipts/TXN889234123.pdf',
    taxCertificateUrl: '/certificates/80G-FY25-26.pdf',
  },
  {
    id: 'don_4',
    transactionId: 'TXN887123982',
    amount: 2500,
    purpose: 'Tribal Education support',
    paymentMethod: 'Credit Card (Visa)',
    status: 'success',
    date: '2026-04-10T00:00:00Z',
    receiptUrl: '/receipts/TXN887123982.pdf',
    taxCertificateUrl: '/certificates/80G-FY25-26.pdf',
  },
  {
    id: 'don_5',
    transactionId: 'TXN884192837',
    amount: 2500,
    purpose: 'Tribal Education support',
    paymentMethod: 'Credit Card (Visa)',
    status: 'success',
    date: '2026-03-10T00:00:00Z',
    receiptUrl: '/receipts/TXN884192837.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_6',
    transactionId: 'TXN881293819',
    amount: 15000,
    purpose: 'Disaster Relief Fund (Assam Floods)',
    paymentMethod: 'UPI (PhonePe)',
    status: 'success',
    date: '2026-02-18T13:40:00Z',
    receiptUrl: '/receipts/TXN881293819.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_7',
    transactionId: 'TXN879283719',
    amount: 2500,
    purpose: 'Tribal Education support',
    paymentMethod: 'Credit Card (Visa)',
    status: 'success',
    date: '2026-02-10T00:00:00Z',
    receiptUrl: '/receipts/TXN879283719.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_8',
    transactionId: 'TXN875182739',
    amount: 1000,
    purpose: 'Plant A Tree Campaign',
    paymentMethod: 'UPI (Paytm)',
    status: 'success',
    date: '2026-01-20T15:10:00Z',
    receiptUrl: '/receipts/TXN875182739.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_9',
    transactionId: 'TXN873918273',
    amount: 2500,
    purpose: 'Tribal Education support',
    paymentMethod: 'Credit Card (Visa)',
    status: 'success',
    date: '2026-01-10T00:00:00Z',
    receiptUrl: '/receipts/TXN873918273.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_10',
    transactionId: 'TXN869283719',
    amount: 5000,
    purpose: 'Winter Blanket Distribution',
    paymentMethod: 'Debit Card (SBI)',
    status: 'success',
    date: '2025-12-15T12:00:00Z',
    receiptUrl: '/receipts/TXN869283719.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_11',
    transactionId: 'TXN865182938',
    amount: 2500,
    purpose: 'Tribal Education support',
    paymentMethod: 'Credit Card (Visa)',
    status: 'success',
    date: '2025-12-10T00:00:00Z',
    receiptUrl: '/receipts/TXN865182938.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_12',
    transactionId: 'TXN861293812',
    amount: 5000,
    purpose: 'Smart Citizen Core Support Fund',
    paymentMethod: 'UPI (GPay)',
    status: 'success',
    date: '2025-11-20T17:30:00Z',
    receiptUrl: '/receipts/TXN861293812.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_13',
    transactionId: 'TXN859283712',
    amount: 2500,
    purpose: 'Medical Aid for Senior Citizens',
    paymentMethod: 'UPI (PhonePe)',
    status: 'failed',
    date: '2025-11-05T14:22:00Z',
  },
  {
    id: 'don_14',
    transactionId: 'TXN851293810',
    amount: 2500,
    purpose: 'Medical Aid for Senior Citizens',
    paymentMethod: 'UPI (PhonePe)',
    status: 'success',
    date: '2025-11-05T14:35:00Z',
    receiptUrl: '/receipts/TXN851293810.pdf',
    taxCertificateUrl: '/certificates/80G-FY24-25.pdf',
  },
  {
    id: 'don_15',
    transactionId: 'TXN849283123',
    amount: 1000,
    purpose: 'Plant A Tree Campaign',
    paymentMethod: 'UPI (GPay)',
    status: 'pending',
    date: '2026-05-27T22:00:00Z',
  }
];

export const mockDonationStats: DonationStats = {
  lifetimeDonated: 48500,
  donatedThisYear: 17500, // Jan 2026 onwards
  donatedLastMonth: 7500,
  totalTransactions: 13,
  averageAmount: 3730.77,
  donorLevel: 'Gold',
};

export const mockRecurringDonations: RecurringDonation[] = [
  {
    id: 'rec_1',
    amount: 2500,
    frequency: 'monthly',
    purpose: 'Tribal Education support',
    status: 'active',
    nextBillingDate: '2026-06-10T00:00:00Z',
    paymentMethod: 'Visa Card ending in 4242',
  },
  {
    id: 'rec_2',
    amount: 1000,
    frequency: 'monthly',
    purpose: 'Plant A Tree Campaign',
    status: 'paused',
    nextBillingDate: '2026-07-20T00:00:00Z',
    paymentMethod: 'UPI Mandate (GPay)',
  }
];

export const mockTaxCertificates: TaxCertificate[] = [
  {
    id: 'tax_1',
    fiscalYear: 'FY 2025-26',
    amount: 17500,
    status: 'generated',
    downloadUrl: '/certificates/80G-FY25-26.pdf',
  },
  {
    id: 'tax_2',
    fiscalYear: 'FY 2024-25',
    amount: 31000,
    status: 'generated',
    downloadUrl: '/certificates/80G-FY24-25.pdf',
  }
];

export const mockReferralMembers: ReferralMember[] = [
  {
    id: 'ref_1',
    name: 'Priya Sharma',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 15000,
    registrationDate: '2026-05-02T10:00:00Z',
    lastActivityDate: '2026-05-22T14:15:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_2',
    name: 'Aarav Patel',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 2500,
    registrationDate: '2026-05-15T09:00:00Z',
    lastActivityDate: '2026-05-21T09:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_3',
    name: 'Vikram Singh',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 5000,
    registrationDate: '2026-04-10T11:30:00Z',
    lastActivityDate: '2026-05-12T16:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_4',
    name: 'Ananya Iyer',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 3000,
    registrationDate: '2026-04-12T14:20:00Z',
    lastActivityDate: '2026-04-20T10:15:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_5',
    name: 'Rohan Gupta',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 1000,
    registrationDate: '2026-04-25T16:45:00Z',
    lastActivityDate: '2026-05-01T11:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_6',
    name: 'Kavita Rao',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 5000,
    registrationDate: '2026-05-01T12:00:00Z',
    lastActivityDate: '2026-05-10T14:30:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_7',
    name: 'Kabir Mehta',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 2500,
    registrationDate: '2026-05-03T15:20:00Z',
    lastActivityDate: '2026-05-05T09:30:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_8',
    name: 'Neha Nair',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 7500,
    registrationDate: '2026-05-04T10:15:00Z',
    lastActivityDate: '2026-05-18T16:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_9',
    name: 'Aditya Verma',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 1000,
    registrationDate: '2026-05-08T09:00:00Z',
    lastActivityDate: '2026-05-11T12:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_10',
    name: 'Meera Deshmukh',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'donated',
    totalDonated: 5000,
    registrationDate: '2026-05-09T14:30:00Z',
    lastActivityDate: '2026-05-24T18:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_11',
    name: 'Siddharth Joshi',
    avatarUrl: undefined,
    status: 'active',
    donationStatus: 'none',
    totalDonated: 0,
    registrationDate: '2026-05-25T11:00:00Z',
    lastActivityDate: '2026-05-25T11:30:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_12',
    name: 'Pooja Reddy',
    avatarUrl: undefined,
    status: 'registered',
    donationStatus: 'none',
    totalDonated: 0,
    registrationDate: '2026-05-26T15:00:00Z',
    lastActivityDate: '2026-05-26T15:00:00Z',
    membershipStatus: 'active',
  },
  {
    id: 'ref_13',
    name: 'Arjun Das',
    avatarUrl: undefined,
    status: 'invited',
    donationStatus: 'none',
    totalDonated: 0,
    registrationDate: '2026-05-27T10:00:00Z',
    lastActivityDate: '2026-05-27T10:00:00Z',
    membershipStatus: 'inactive',
  }
];

export const mockReferralStats: ReferralStats = {
  totalInvited: 15,
  joinedCount: 12,
  activeDonorsCount: 10,
  totalContributionGenerated: 47000,
  referralCode: 'SC-SEB-4923',
  referralLink: 'https://smartcitizen.org/signup?ref=SC-SEB-4923',
};

export const mockMemberProfile: MemberProfile = {
  id: 'usr_1',
  name: 'Sebastian Sultz',
  email: 'sebastian@smartcitizen.org',
  phone: '+91 98765 43210',
  dob: '1995-08-15',
  profilePhoto: undefined,
  userType: 'member',
  memberId: 'SC-2026-98124',
  joinDate: '2026-01-10T00:00:00Z',
  status: 'active',
  address: 'Flat 402, Green Meadows, Juhu Lane',
  city: 'Mumbai',
  district: 'Mumbai Suburban',
  state: 'Maharashtra',
  pincode: '400049',
  linkedinUrl: 'https://linkedin.com/in/sebastiansultz',
  twitterUrl: 'https://twitter.com/sebastiansultz',
  facebookUrl: '',
};

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'tkt_1',
    ticketId: 'SC-4820',
    category: 'donation',
    subject: '80G Certificate Generation Request',
    description: 'My donation of ₹15,000 for disaster relief on Feb 18 is not showing up in the FY 2024-25 80G tax document. Requesting correction.',
    priority: 'medium',
    status: 'resolved',
    createdAt: '2026-05-03T09:00:00Z',
    updatedAt: '2026-05-05T11:20:00Z',
    messages: [
      {
        id: 'msg_1_1',
        sender: 'user',
        senderName: 'Sebastian Sultz',
        content: 'Hi support team, my tax certificate for FY 24-25 does not reflect the donation of ₹15,000 made on Feb 18. Please assist.',
        timestamp: '2026-05-03T09:00:00Z',
      },
      {
        id: 'msg_1_2',
        sender: 'agent',
        senderName: 'Neha (Support Team)',
        content: 'Hi Sebastian, thank you for reaching out. We are verifying the bank settlement details for your transaction TXN881293819. We will update you shortly.',
        timestamp: '2026-05-04T10:15:00Z',
      },
      {
        id: 'msg_1_3',
        sender: 'agent',
        senderName: 'Neha (Support Team)',
        content: 'Hi Sebastian, the issue has been resolved. The transaction was verified and your FY 2024-25 80G tax certificate has been re-generated. You can now download it directly from your dashboard.',
        timestamp: '2026-05-05T11:20:00Z',
      },
      {
        id: 'msg_1_4',
        sender: 'user',
        senderName: 'Sebastian Sultz',
        content: 'Awesome, verified. Thank you for the quick resolution!',
        timestamp: '2026-05-05T12:00:00Z',
      }
    ],
  },
  {
    id: 'tkt_2',
    ticketId: 'SC-4912',
    category: 'volunteer',
    subject: 'Eligibility criteria clarification',
    description: 'I have invited 12 friends and 10 have joined, but I am still not shown as eligible for volunteer application. Please clarify.',
    priority: 'low',
    status: 'open',
    createdAt: '2026-05-26T14:30:00Z',
    updatedAt: '2026-05-26T14:30:00Z',
    messages: [
      {
        id: 'msg_2_1',
        sender: 'user',
        senderName: 'Sebastian Sultz',
        content: 'I have met the 10 referred members threshold, but the volunteer application is still locked. Can you please check?',
        timestamp: '2026-05-26T14:30:00Z',
      }
    ],
  },
  {
    id: 'tkt_3',
    ticketId: 'SC-4925',
    category: 'technical',
    subject: 'Profile photo upload failing',
    description: 'Trying to upload a JPG image of size 1.2MB, but it fails with "Internal Server Error".',
    priority: 'medium',
    status: 'in_progress',
    createdAt: '2026-05-27T08:00:00Z',
    updatedAt: '2026-05-27T10:00:00Z',
    messages: [
      {
        id: 'msg_3_1',
        sender: 'user',
        senderName: 'Sebastian Sultz',
        content: 'Whenever I try to upload my profile photo, I get an upload failure. The image is a standard JPG and within the size limit.',
        timestamp: '2026-05-27T08:00:00Z',
      },
      {
        id: 'msg_3_2',
        sender: 'agent',
        senderName: 'Rahul (Tech Support)',
        content: 'Hello Sebastian. We are looking into this. It appears to be an issue with our image processing service handles certain color profiles. Can you try uploading another image or email the photo to us directly so we can inspect?',
        timestamp: '2026-05-27T10:00:00Z',
      }
    ],
  }
];

export const mockFAQs: FAQItem[] = [
  {
    id: 'faq_1',
    category: 'general',
    question: 'What is the Smart Citizen ID?',
    answer: 'The Smart Citizen ID is your unique identifier as a registered member of our platform. It helps us match your offline contributions, event participation, and volunteer sessions to your profile.',
  },
  {
    id: 'faq_2',
    category: 'donation',
    question: 'How do I claim my 80G tax benefits?',
    answer: 'All contributions made to our NGO are eligible for 50% tax deduction under Section 80G of the Income Tax Act. You can download the 80G tax certificate directly from the "My Donations" section under the "Tax Certificates" tab after the end of each financial year.',
  },
  {
    id: 'faq_3',
    category: 'volunteer',
    question: 'What are the requirements to become an active Volunteer?',
    answer: 'To apply as an official volunteer, you need to invite at least 10 friends to join our Smart Citizen network using your unique referral link, and at least 10 must successfully register. This demonstrates community alignment and engagement before joining as a volunteer.',
  },
  {
    id: 'faq_4',
    category: 'donation',
    question: 'Can I cancel or pause my monthly recurring donation?',
    answer: 'Yes, you can pause or cancel your monthly donation subscription at any time under the "My Donations" section in the "Recurring Donations" tab. No questions asked.',
  },
  {
    id: 'faq_5',
    category: 'account',
    question: 'How do I change my registered mobile number?',
    answer: 'To update your mobile number, please open a support ticket under the "Support" tab. For security reasons, changes to primary contact details require verification by our admin team.',
  },
  {
    id: 'faq_6',
    category: 'volunteer',
    question: 'What types of activities do volunteers do?',
    answer: 'Volunteers assist in field drives (clean-ups, plantation drives), administrative coordination, content writing, digital outreach, and teaching in tribal schools. You can list your skills and preferences in the application form.',
  },
  {
    id: 'faq_7',
    category: 'donation',
    question: 'Are my payment details secure?',
    answer: 'Absolutely. We do not store credit card or net banking details on our servers. All transactions are securely processed through Razorpay/Stripe using industry-standard PCI-DSS encryption.',
  },
  {
    id: 'faq_8',
    category: 'general',
    question: 'How can I participate in campaigns?',
    answer: 'Active campaigns are listed on the public homepage. Once you are logged in, you can click "Join Campaign" to receive updates, event details, and logging information for that specific movement.',
  }
];

export const mockVolunteerEligibility: VolunteerEligibility = {
  invitedCount: 15,
  joinedCount: 12, // More than 10, so they are eligible!
  donatedCount: 10,
  isEligible: true,
  requiredInvited: 10,
  requiredJoined: 10,
  requiredDonated: 0, // No donation required from referrals to apply
};
